version: '3.8'

services:
  # Postgres
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"   # management UI

  # Kong API Gateway
  kong:
    image: kong:2.8
    container_name: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=${POSTGRES_HOST}
      - KONG_PG_USER=${POSTGRES_USER}
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD}
      - KONG_PG_DATABASE=${POSTGRES_DB}
    ports:
      - "${KONG_PROXY_PORT}:8000"
      - "${KONG_ADMIN_PORT}:8001"
    depends_on:
      postgres:
        condition: service_healthy

  # Konga Dashboard (disabilitata per ora)
  # konga:
  #   image: pantsel/konga:latest
  #   container_name: konga
  #   ports:
  #     - "${KONGA_PORT}:1337"
  #   depends_on:
  #     kong:
  #       condition: service_healthy
  #   environment:
  #     - DB_ADAPTER=sqlite
  #     - DB_FILE=/db/konga.sqlite
  #   volumes:
  #     - ./data/konga:/db
